import { describe, it, expect } from '@jest/globals'
import * as testData from './data/budget.json'
import * as geoserverData from './data/geoserver.json'

function findMissingItems(
  firstArray: string[],
  secondArray: string[]
): string[] {
  // Convert arrays to sets for efficient comparison
  const firstSet = new Set(firstArray)
  const secondSet = new Set(secondArray)

  // Find the items that are in the first set but not in the second set
  const missingItems = new Set(
    [...firstSet].filter((item) => !secondSet.has(item))
  )

  return Array.from(missingItems)
}

describe('budget data script', () => {
  describe('Localities', () => {
    const testLocalities = testData.filter(
      (itm) => itm.area_type === 'locality'
    )
    const geoserverDataLocalities = geoserverData.features.filter(
      (itm) => itm.properties.type === 'locality'
    )

    it('should have the same count of localities as the geoserver data', () => {
      const testLocalitiesPairs = testLocalities.map(
        (itm) =>
          `${itm.name.toUpperCase()} - ${itm.lga_official_name.toUpperCase()}`
      )
      const geoServerLocalitiesPairs = geoserverDataLocalities.map(
        (itm) => `${itm.properties.name} - ${itm.properties.lga_official_name}`
      )
      const missingInTestData: string[] = findMissingItems(
        geoServerLocalitiesPairs,
        testLocalitiesPairs
      )
      expect(missingInTestData).toMatchInlineSnapshot(`
        [
          "AREEGRA - BULOKE SHIRE",
          "ATHLONE - SOUTH GIPPSLAND SHIRE",
          "BALMORAL - HORSHAM RURAL CITY",
          "BARINGHUP WEST - CENTRAL GOLDFIELDS SHIRE",
          "BARWON DOWNS - SURF COAST SHIRE",
          "BAYNTON - MITCHELL SHIRE",
          "BAYSWATER NORTH - KNOX CITY",
          "BEACONSFIELD UPPER - CASEY CITY",
          "BENGWORDEN - WELLINGTON SHIRE",
          "BERWICK - CARDINIA SHIRE",
          "BLACKBURN NORTH - MANNINGHAM CITY",
          "BULLEEN - BOROONDARA CITY",
          "BULLENGAROOK - MOORABOOL SHIRE",
          "CALLIGNEE - WELLINGTON SHIRE",
          "CALLIGNEE NORTH - LATROBE CITY",
          "CHERRYPOOL - NORTHERN GRAMPIANS SHIRE",
          "COLDSTREAM - NILLUMBIK SHIRE",
          "CONDAH - MOYNE SHIRE",
          "DEER PARK - MELTON CITY",
          "DIMBOOLA - HORSHAM RURAL CITY",
          "DROPMORE - MITCHELL SHIRE",
          "DROPMORE - STRATHBOGIE SHIRE",
          "EDGECOMBE - MOUNT ALEXANDER SHIRE",
          "EILDON - YARRA RANGES SHIRE",
          "ELIZABETH ISLAND - FRENCH-ELIZABETH-SANDSTONE ISLANDS (UNINC)",
          "ESSENDON - MERRI-BEK CITY",
          "FRENCH ISLAND - FRENCH-ELIZABETH-SANDSTONE ISLANDS (UNINC)",
          "GISBORNE - MELTON CITY",
          "GLENORCHY - HORSHAM RURAL CITY",
          "HARKAWAY - CARDINIA SHIRE",
          "HAWTHORN - STONNINGTON CITY",
          "INDIGO VALLEY - WODONGA CITY",
          "KANGAROO GROUND - MANNINGHAM CITY",
          "KEW - YARRA CITY",
          "KINGLAKE WEST - MITCHELL SHIRE",
          "KOOYONG - BOROONDARA CITY",
          "LORNE - COLAC OTWAY SHIRE",
          "LOWER PLENTY - MANNINGHAM CITY",
          "MARYSVILLE - YARRA RANGES SHIRE",
          "MIGA LAKE - HORSHAM RURAL CITY",
          "MINCHA WEST - LODDON SHIRE",
          "MINYIP - BULOKE SHIRE",
          "MONT ALBERT NORTH - MANNINGHAM CITY",
          "MURCHISON - CAMPASPE SHIRE",
          "NARRE WARREN EAST - CARDINIA SHIRE",
          "OFFICER SOUTH - CASEY CITY",
          "POINT COOK - HOBSONS BAY CITY",
          "REDESDALE - MITCHELL SHIRE",
          "RINGWOOD - KNOX CITY",
          "TOOBORAC - MACEDON RANGES SHIRE",
          "WAIL - HINDMARSH SHIRE",
          "WAL WAL - HORSHAM RURAL CITY",
          "WANTIRNA - MAROONDAH CITY",
          "WONNANGATTA - WELLINGTON SHIRE",
        ]
      `)
      const missingInGeoData: string[] = findMissingItems(
        testLocalitiesPairs,
        geoServerLocalitiesPairs
      )
      expect(missingInGeoData).toMatchInlineSnapshot(`
        [
          "ELIZABETH ISLAND - FRENCH-ELIZABETH-SANDSTONE ISLANDS (UNINCORPO",
          "FRENCH ISLAND - FRENCH-ELIZABETH-SANDSTONE ISLANDS (UNINCORPO",
          "WARRANWOOD - MANNINGHAM CITY",
          "WATTLE HILL - COLAC OTWAY SHIRE",
        ]
      `)
    })
  })
  describe('LGAs', () => {
    it('should have the correct number of LGAs', () => {
      const testLGAs = testData.filter((itm) => itm.area_type === 'lga')
      expect(testLGAs.length).toEqual(79)
    })
  })
  describe('Postcodes', () => {
    it('should have the correct number of Postcodes', () => {
      const postcodes = testData.filter((itm) => itm.area_type === 'postcode')
      expect(postcodes.length).toEqual(1424)
    })
    it('should have no null lga values', () => {
      const postcodes = testData.filter((itm) => itm.area_type === 'postcode')
      expect(postcodes.every((itm) => itm.lga_code !== null)).toBeTruthy()
    })
    it('should have a bbox for each LGA', () => {
      const postcodes = testData.filter((itm) => itm.area_type === 'postcode')
      expect(
        postcodes.every((itm) => itm.lga_bbox && Array.isArray(itm.lga_bbox))
      ).toBeTruthy()
    })
    it('should have the same number of postcode / lga pairs as geoserver dataset', () => {
      const postcodes = testData.filter((itm) => itm.area_type === 'postcode')
      const geoserverDataPostcodes = geoserverData.features.filter(
        (itm) => itm.properties.type === 'postcode'
      )

      const testPostcodes = postcodes.map(
        (itm) =>
          `${itm.name.toUpperCase()} - ${itm.lga_official_name.toUpperCase()}`
      )
      const geoServerPostcodes = geoserverDataPostcodes.map(
        (itm) => `${itm.properties.name} - ${itm.properties.lga_official_name}`
      )

      const missingInTestData: string[] = findMissingItems(
        geoServerPostcodes,
        testPostcodes
      )
      expect(missingInTestData).toMatchInlineSnapshot(`
        [
          "3030 - HOBSONS BAY CITY",
          "3134 - KNOX CITY",
          "3551 - LODDON SHIRE",
          "3559 - GREATER BENDIGO CITY",
          "3646 - STRATHBOGIE SHIRE",
          "3691 - ALPINE SHIRE",
          "3691 - INDIGO SHIRE",
          "3691 - WODONGA CITY",
          "3701 - EAST GIPPSLAND SHIRE",
          "3713 - YARRA RANGES SHIRE",
          "3722 - MOUNT BULLER ALPINE RESORT (UNINCORPORATED)",
          "3722 - MOUNT STIRLING ALPINE RESORT (UNINCORPORATED)",
          "3921 - FRENCH-ELIZABETH-SANDSTONE ISLANDS (UNINC)",
          "3951 - BASS COAST SHIRE",
        ]
      `)

      const missingInGeoData: string[] = findMissingItems(
        testPostcodes,
        geoServerPostcodes
      )
      expect(missingInGeoData).toMatchInlineSnapshot(`
        [
          "3003 - MARIBYRNONG CITY",
          "3008 - PORT PHILLIP CITY",
          "3011 - MELBOURNE CITY",
          "3011 - MOONEE VALLEY CITY",
          "3012 - WYNDHAM CITY",
          "3012 - MOONEE VALLEY CITY",
          "3013 - HOBSONS BAY CITY",
          "3013 - MELBOURNE CITY",
          "3015 - MARIBYRNONG CITY",
          "3015 - MELBOURNE CITY",
          "3019 - BRIMBANK CITY",
          "3019 - MOONEE VALLEY CITY",
          "3020 - WYNDHAM CITY",
          "3020 - MARIBYRNONG CITY",
          "3020 - MOONEE VALLEY CITY",
          "3021 - MELTON CITY",
          "3025 - WYNDHAM CITY",
          "3025 - MARIBYRNONG CITY",
          "3026 - HOBSONS BAY CITY",
          "3026 - MELTON CITY",
          "3029 - BRIMBANK CITY",
          "3030 - GREATER GEELONG CITY",
          "3031 - MARIBYRNONG CITY",
          "3032 - MERRI-BEK CITY",
          "3032 - MELBOURNE CITY",
          "3034 - MARIBYRNONG CITY",
          "3034 - BRIMBANK CITY",
          "3039 - MERRI-BEK CITY",
          "3040 - MARIBYRNONG CITY",
          "3041 - MERRI-BEK CITY",
          "3042 - HUME CITY",
          "3043 - MOONEE VALLEY CITY",
          "3044 - MOONEE VALLEY CITY",
          "3045 - BRIMBANK CITY",
          "3046 - HUME CITY",
          "3046 - MOONEE VALLEY CITY",
          "3047 - MERRI-BEK CITY",
          "3051 - MOONEE VALLEY CITY",
          "3052 - MOONEE VALLEY CITY",
          "3054 - MERRI-BEK CITY",
          "3055 - MELBOURNE CITY",
          "3055 - MOONEE VALLEY CITY",
          "3057 - DAREBIN CITY",
          "3060 - DAREBIN CITY",
          "3061 - WHITTLESEA CITY",
          "3062 - WHITTLESEA CITY",
          "3064 - MACEDON RANGES SHIRE",
          "3064 - MITCHELL SHIRE",
          "3066 - MELBOURNE CITY",
          "3067 - BOROONDARA CITY",
          "3068 - DAREBIN CITY",
          "3070 - YARRA CITY",
          "3070 - MERRI-BEK CITY",
          "3071 - BANYULE CITY",
          "3071 - MERRI-BEK CITY",
          "3072 - BANYULE CITY",
          "3072 - MERRI-BEK CITY",
          "3073 - BANYULE CITY",
          "3073 - MERRI-BEK CITY",
          "3073 - WHITTLESEA CITY",
          "3074 - HUME CITY",
          "3074 - DAREBIN CITY",
          "3075 - HUME CITY",
          "3076 - HUME CITY",
          "3078 - BANYULE CITY",
          "3078 - BOROONDARA CITY",
          "3079 - MANNINGHAM CITY",
          "3079 - YARRA CITY",
          "3079 - BOROONDARA CITY",
          "3079 - DAREBIN CITY",
          "3081 - DAREBIN CITY",
          "3082 - NILLUMBIK SHIRE",
          "3083 - NILLUMBIK SHIRE",
          "3084 - MANNINGHAM CITY",
          "3087 - NILLUMBIK SHIRE",
          "3088 - WHITTLESEA CITY",
          "3090 - WHITTLESEA CITY",
          "3091 - WHITTLESEA CITY",
          "3093 - NILLUMBIK SHIRE",
          "3094 - NILLUMBIK SHIRE",
          "3095 - MANNINGHAM CITY",
          "3099 - WHITTLESEA CITY",
          "3102 - BANYULE CITY",
          "3102 - YARRA CITY",
          "3104 - BANYULE CITY",
          "3104 - MANNINGHAM CITY",
          "3105 - BANYULE CITY",
          "3106 - BANYULE CITY",
          "3106 - NILLUMBIK SHIRE",
          "3107 - BANYULE CITY",
          "3108 - BOROONDARA CITY",
          "3108 - WHITEHORSE CITY",
          "3109 - WHITEHORSE CITY",
          "3111 - MAROONDAH CITY",
          "3111 - WHITEHORSE CITY",
          "3115 - NILLUMBIK SHIRE",
          "3116 - NILLUMBIK SHIRE",
          "3116 - MAROONDAH CITY",
          "3116 - MANNINGHAM CITY",
          "3121 - BOROONDARA CITY",
          "3121 - STONNINGTON CITY",
          "3121 - MELBOURNE CITY",
          "3122 - YARRA CITY",
          "3123 - STONNINGTON CITY",
          "3129 - BOROONDARA CITY",
          "3132 - MANNINGHAM CITY",
          "3135 - KNOX CITY",
          "3136 - MANNINGHAM CITY",
          "3136 - YARRA RANGES SHIRE",
          "3137 - KNOX CITY",
          "3138 - MAROONDAH CITY",
          "3141 - YARRA CITY",
          "3142 - YARRA CITY",
          "3142 - BOROONDARA CITY",
          "3144 - GLEN EIRA CITY",
          "3145 - BOROONDARA CITY",
          "3145 - MONASH CITY",
          "3148 - STONNINGTON CITY",
          "3150 - KNOX CITY",
          "3152 - WHITEHORSE CITY",
          "3152 - MONASH CITY",
          "3153 - YARRA RANGES SHIRE",
          "3154 - YARRA RANGES SHIRE",
          "3155 - MAROONDAH CITY",
          "3155 - YARRA RANGES SHIRE",
          "3160 - CARDINIA SHIRE",
          "3161 - STONNINGTON CITY",
          "3163 - MONASH CITY",
          "3165 - KINGSTON CITY",
          "3165 - MONASH CITY",
          "3167 - GLEN EIRA CITY",
          "3169 - GREATER DANDENONG CITY",
          "3170 - KNOX CITY",
          "3171 - MONASH CITY",
          "3173 - KINGSTON CITY",
          "3175 - KNOX CITY",
          "3175 - KINGSTON CITY",
          "3175 - CASEY CITY",
          "3175 - FRANKSTON CITY",
          "3175 - MONASH CITY",
          "3177 - GREATER DANDENONG CITY",
          "3178 - CASEY CITY",
          "3178 - GREATER DANDENONG CITY",
          "3178 - MONASH CITY",
          "3179 - MONASH CITY",
          "3184 - BAYSIDE CITY",
          "3186 - PORT PHILLIP CITY",
          "3188 - KINGSTON CITY",
          "3189 - BAYSIDE CITY",
          "3195 - GREATER DANDENONG CITY",
          "3196 - GREATER DANDENONG CITY",
          "3197 - FRANKSTON CITY",
          "3199 - MORNINGTON PENINSULA SHIRE",
          "3201 - KINGSTON CITY",
          "3204 - BAYSIDE CITY",
          "3204 - KINGSTON CITY",
          "3207 - HOBSONS BAY CITY",
          "3207 - MARIBYRNONG CITY",
          "3212 - WYNDHAM CITY",
          "3216 - SURF COAST SHIRE",
          "3218 - SURF COAST SHIRE",
          "3221 - GOLDEN PLAINS SHIRE",
          "3228 - GREATER GEELONG CITY",
          "3234 - SURF COAST SHIRE",
          "3240 - GREATER GEELONG CITY",
          "3241 - GOLDEN PLAINS SHIRE",
          "3260 - MOYNE SHIRE",
          "3269 - COLAC OTWAY SHIRE",
          "3272 - CORANGAMITE SHIRE",
          "3275 - WARRNAMBOOL CITY",
          "3286 - SOUTHERN GRAMPIANS SHIRE",
          "3287 - SOUTHERN GRAMPIANS SHIRE",
          "3294 - MOYNE SHIRE",
          "3300 - GLENELG SHIRE",
          "3303 - SOUTHERN GRAMPIANS SHIRE",
          "3317 - HORSHAM RURAL CITY",
          "3318 - SOUTHERN GRAMPIANS SHIRE",
          "3325 - ARARAT RURAL CITY",
          "3325 - PYRENEES SHIRE",
          "3325 - MOYNE SHIRE",
          "3331 - GREATER GEELONG CITY",
          "3337 - MOORABOOL SHIRE",
          "3338 - MOORABOOL SHIRE",
          "3342 - GREATER GEELONG CITY",
          "3350 - MOORABOOL SHIRE",
          "3351 - CORANGAMITE SHIRE",
          "3352 - CENTRAL GOLDFIELDS SHIRE",
          "3356 - GOLDEN PLAINS SHIRE",
          "3361 - GOLDEN PLAINS SHIRE",
          "3370 - BALLARAT CITY",
          "3378 - PYRENEES SHIRE",
          "3379 - SOUTHERN GRAMPIANS SHIRE",
          "3387 - YARRIAMBIACK SHIRE",
          "3391 - BULOKE SHIRE",
          "3392 - NORTHERN GRAMPIANS SHIRE",
          "3396 - BULOKE SHIRE",
          "3407 - WEST WIMMERA SHIRE",
          "3409 - HINDMARSH SHIRE",
          "3413 - HINDMARSH SHIRE",
          "3415 - HINDMARSH SHIRE",
          "3418 - HORSHAM RURAL CITY",
          "3420 - HINDMARSH SHIRE",
          "3423 - YARRIAMBIACK SHIRE",
          "3427 - BRIMBANK CITY",
          "3428 - BRIMBANK CITY",
          "3429 - MACEDON RANGES SHIRE",
          "3429 - MELTON CITY",
          "3430 - MITCHELL SHIRE",
          "3431 - HUME CITY",
          "3434 - MITCHELL SHIRE",
          "3437 - HUME CITY",
          "3442 - MOORABOOL SHIRE",
          "3448 - GREATER BENDIGO CITY",
          "3462 - CENTRAL GOLDFIELDS SHIRE",
          "3463 - GREATER BENDIGO CITY",
          "3472 - PYRENEES SHIRE",
          "3477 - CENTRAL GOLDFIELDS SHIRE",
          "3478 - LODDON SHIRE",
          "3483 - YARRIAMBIACK SHIRE",
          "3487 - BULOKE SHIRE",
          "3489 - BULOKE SHIRE",
          "3490 - YARRIAMBIACK SHIRE",
          "3490 - SWAN HILL RURAL CITY",
          "3522 - GREATER BENDIGO CITY",
          "3525 - NORTHERN GRAMPIANS SHIRE",
          "3530 - GANNAWARRA SHIRE",
          "3530 - SWAN HILL RURAL CITY",
          "3533 - YARRIAMBIACK SHIRE",
          "3533 - MILDURA RURAL CITY",
          "3537 - BULOKE SHIRE",
          "3540 - LODDON SHIRE",
          "3542 - SWAN HILL RURAL CITY",
          "3544 - GANNAWARRA SHIRE",
          "3546 - BULOKE SHIRE",
          "3546 - MILDURA RURAL CITY",
          "3549 - MILDURA RURAL CITY",
          "3561 - GREATER BENDIGO CITY",
          "3564 - LODDON SHIRE",
          "3566 - LODDON SHIRE",
          "3566 - GANNAWARRA SHIRE",
          "3567 - CAMPASPE SHIRE",
          "3570 - CAMPASPE SHIRE",
          "3571 - GREATER BENDIGO CITY",
          "3572 - GREATER BENDIGO CITY",
          "3575 - GANNAWARRA SHIRE",
          "3575 - CAMPASPE SHIRE",
          "3583 - GANNAWARRA SHIRE",
          "3584 - GANNAWARRA SHIRE",
          "3585 - BULOKE SHIRE",
          "3607 - MITCHELL SHIRE",
          "3608 - MITCHELL SHIRE",
          "3612 - GREATER SHEPPARTON CITY",
          "3616 - CAMPASPE SHIRE",
          "3618 - CAMPASPE SHIRE",
          "3620 - MOIRA SHIRE",
          "3621 - MOIRA SHIRE",
          "3624 - GREATER SHEPPARTON CITY",
          "3629 - MOIRA SHIRE",
          "3629 - CAMPASPE SHIRE",
          "3631 - MOIRA SHIRE",
          "3635 - GREATER SHEPPARTON CITY",
          "3636 - GREATER SHEPPARTON CITY",
          "3638 - GREATER SHEPPARTON CITY",
          "3638 - CAMPASPE SHIRE",
          "3639 - CAMPASPE SHIRE",
          "3658 - WHITTLESEA CITY",
          "3659 - MURRINDINDI SHIRE",
          "3662 - STRATHBOGIE SHIRE",
          "3662 - GREATER BENDIGO CITY",
          "3666 - GREATER SHEPPARTON CITY",
          "3678 - ALPINE SHIRE",
          "3678 - MANSFIELD SHIRE",
          "3678 - WELLINGTON SHIRE",
          "3678 - BENALLA RURAL CITY",
          "3678 - INDIGO SHIRE",
          "3683 - WANGARATTA RURAL CITY",
          "3685 - MOIRA SHIRE",
          "3695 - WODONGA CITY",
          "3695 - ALPINE SHIRE",
          "3697 - TOWONG SHIRE",
          "3699 - TOWONG SHIRE",
          "3700 - INDIGO SHIRE",
          "3714 - MANSFIELD SHIRE",
          "3715 - STRATHBOGIE SHIRE",
          "3719 - STRATHBOGIE SHIRE",
          "3720 - MURRINDINDI SHIRE",
          "3723 - BAW BAW SHIRE",
          "3725 - MOIRA SHIRE",
          "3725 - STRATHBOGIE SHIRE",
          "3726 - MOIRA SHIRE",
          "3727 - GREATER SHEPPARTON CITY",
          "3727 - BENALLA RURAL CITY",
          "3730 - WANGARATTA RURAL CITY",
          "3730 - INDIGO SHIRE",
          "3735 - ALPINE SHIRE",
          "3737 - MOUNT HOTHAM ALPINE RESORT (UNINCORPORATED)",
          "3737 - WANGARATTA RURAL CITY",
          "3746 - INDIGO SHIRE",
          "3747 - ALPINE SHIRE",
          "3749 - WODONGA CITY",
          "3749 - ALPINE SHIRE",
          "3750 - HUME CITY",
          "3752 - NILLUMBIK SHIRE",
          "3753 - MACEDON RANGES SHIRE",
          "3753 - HUME CITY",
          "3756 - WHITTLESEA CITY",
          "3763 - YARRA RANGES SHIRE",
          "3775 - MURRINDINDI SHIRE",
          "3775 - MANNINGHAM CITY",
          "3779 - BAW BAW SHIRE",
          "3781 - YARRA RANGES SHIRE",
          "3783 - BAW BAW SHIRE",
          "3783 - YARRA RANGES SHIRE",
          "3785 - KNOX CITY",
          "3791 - CARDINIA SHIRE",
          "3797 - CARDINIA SHIRE",
          "3797 - BAW BAW SHIRE",
          "3799 - MURRINDINDI SHIRE",
          "3799 - BAW BAW SHIRE",
          "3802 - GREATER DANDENONG CITY",
          "3803 - GREATER DANDENONG CITY",
          "3808 - YARRA RANGES SHIRE",
          "3815 - BAW BAW SHIRE",
          "3818 - CARDINIA SHIRE",
          "3823 - SOUTH GIPPSLAND SHIRE",
          "3825 - MANSFIELD SHIRE",
          "3825 - YARRA RANGES SHIRE",
          "3833 - CARDINIA SHIRE",
          "3840 - BAW BAW SHIRE",
          "3844 - BAW BAW SHIRE",
          "3851 - EAST GIPPSLAND SHIRE",
          "3858 - ALPINE SHIRE",
          "3858 - WANGARATTA RURAL CITY",
          "3858 - BAW BAW SHIRE",
          "3898 - TOWONG SHIRE",
          "3898 - WELLINGTON SHIRE",
          "3910 - CASEY CITY",
          "3911 - CASEY CITY",
          "3912 - FRANKSTON CITY",
          "3921 - FRENCH-ELIZABETH-SANDSTONE ISLANDS (UNINCORPO",
          "3930 - FRANKSTON CITY",
          "3946 - BASS COAST SHIRE",
          "3956 - BASS COAST SHIRE",
          "3960 - LATROBE CITY",
          "3960 - WELLINGTON SHIRE",
          "3962 - LATROBE CITY",
          "3965 - WELLINGTON SHIRE",
          "3971 - SOUTH GIPPSLAND SHIRE",
          "3975 - FRANKSTON CITY",
          "3976 - GREATER DANDENONG CITY",
          "3981 - CASEY CITY",
          "3987 - BASS COAST SHIRE",
          "3988 - CARDINIA SHIRE",
        ]
      `)
    })
  })
})
