name: Docs
on:
  push:
    paths:
      - '.github/workflows/docs.yml'
      - 'docs'
      - 'packages/ripple-ui-core/**'
      - 'packages/ripple-ui-forms/**'
      - 'pnpm-lock.yaml'
jobs:
  Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.0.6
          run_install: false
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install Dependencies
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: pnpm install --frozen-lockfile
      - name: Build docs
        run: pnpm run build:docs
