name: Vue
on:
  push:
    paths:
      - '.github/workflows/vue.yml'
      - 'examples/vue-app/**'
      - 'packages/ripple-ui-core/**'
      - 'packages/ripple-ui-forms/**'
      - 'pnpm-lock.yaml'
jobs:
  Examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.1.3
          run_install: false

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: pnpm install --frozen-lockfile

      - name: Build Example Vue app
        run: pnpm -F vue-app build
