name: Webcomponents
on:
  push:
    paths:
      - '.github/workflows/webcomponents.yml'
      - 'examples/webcomponents/**'
      - 'packages/ripple-ui-core/**'
      - 'packages/ripple-ui-forms/**'
      - 'pnpm-lock.yaml'
jobs:
  Examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.0.6
          run_install: false

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: pnpm install --frozen-lockfile

      - name: Build Example Webcomponents app
        run: pnpm -F webcomponents build
